### ISSUE TITLE
Some features added to your original skeleton

### ISSUE THREAD

**Issue by eedugon** [sscaling/docker-jmx-prometheus-exporter#1]
Hello,

FYI, I have created a dockerized version of jmx-exporter starting from your original skeleton.
https://github.com/eedugon/jmx-exporter-dockerized

I have added some features like dynamic configuration from environment variables provided when creating the docker.

Regards!
Eduardo

**Comment by sscaling** [comment]
Glad you found it useful. The recommended way of running JMX exporter is as an agent so I've not provided a whole bunch of config options as this is generally more useful as a development / test utility. Reloading the whole config file is more useful in this scenario as that will become the agent config in a production environment. Thanks!
